site_name: Atma's blog
site_url: https://atmamani.github.io
docs_dir: src
site_dir: docs
nav:
  - Home: index.md
  - Projects:
    - Cloud:
      - projects/cloud/index.md
      - Argo Workflows: projects/cloud/argo.md
      - Intro to GCP: projects/cloud/gcp-1.md
      - Intro to GKE: projects/cloud/gke-1.md
      - GKE Objects and specs: projects/cloud/gke-2.md
    - Deep Learning:
      - projects/dl/index.md
      - Configure GPU on windows: projects/dl/configure-gpu-windows.md
      - Setup for FastAI v1: projects/dl/setup-win-fastai-v1.md
      - Setup for FastAI v2: projects/dl/setup-win-fastai-v2.md
      - Getting started with FastAI: projects/dl/fastai/fastai-1.ipynb
      - Image classification with FastAI: projects/dl/fastai/lesson1-pets.ipynb
      - Concepts - `vision` module of FastAI: projects/dl/fastai/vision.md
      - Concepts - Neural Nets: projects/dl/coursera-neural-nets-concepts.md
      - Concepts - Backpropagation: projects/dl/coursera-understanding-backpropagation.md
    - Machine Learning:
      - projects/ml/index.md
      - Core Concepts:
        - ML Concepts: projects/ml/ml-concepts.md
        - Scikit Learn syntax: projects/ml/sklearn-1.ipynb
        - Understanding Gradient Descent: projects/ml/gradient-descent.md
        - A primer on linear algebra: projects/ml/linear-algebra.md
        - Naive Bayes classification with sklearn: projects/ml/sklearn_naive_bayes_classifier.ipynb
      - Generalized linear models:
        - Linear regression concepts: projects/stats/islr/03_linear_regression.ipynb
        - Solving multivariate linear regression: projects/ml/multivariate-linear-regression.md
        - Analytical vs Gradient Descent methods for linear regression: projects/ml/linear-regression-analytical-solution.md
        - Logistic regression concepts: projects/ml/logistic-reg-concepts.md
        - Model regularization: projects/ml/model-regularization.md
      - Applications:
        - Implementing Gradient Descent for linear regression: projects/ml/gradient-descent-in-python.ipynb
        - Applying Linear Regression with `sklearn` and `statmodels: projects/ml/sklearn_statmodels_linear_regression.ipynb
        - Implementing Gradient Descent for logistic regression: projects/ml/implementing-logistic-regression-in-python.ipynb
        - MNIST digits classification using Logistic regression in Scikit-Learn: projects/ml/mnist-digits-classification-using-logistic-regression-scikit-learn.ipynb
    - Statistics:
      - projects/stats/index.md
      - Collecting data: projects/stats/01_data_collection.ipynb
      - Describing data: projects/stats/02_data_description.ipynb
      - Conditional probability: projects/stats/04_conditional_probability.ipynb
      - Normal distribution: projects/stats/04_normal_distribution.ipynb
      - Binomial and Poisson distributions: projects/stats/04_probability_distributions_binomial_poisson.ipynb
      - Hypothesis testing: projects/stats/05_hypothesis_testing.ipynb
      - Statistical learning: projects/stats/islr/02_stat_learning.ipynb
      - Linear regression concepts: projects/stats/islr/03_linear_regression.ipynb
    - Distributed Computing:
      - PySpark an Introduction: projects/dist-computing/pyspark/getting-started-pyspark.md
      - SparkMLLib - Predicting house prices: projects/dist-computing/pyspark/spark-ml-ca-housing.ipynb
      - Dask - Preparing larger-than-memory hurricane data: projects/dist-computing/dask/part1_prepare_hurricane_data.ipynb
      - Dask - EDA on hurricane tracks: projects/dist-computing/dask/part2_explore_hurricane_tracks.ipynb
      - Dask - Does intensity of hurricanes increase over time?: projects/dist-computing/dask/part3_analyze_hurricane_tracks.ipynb
    - Spatial Analysis:
      - Spatial data structures: projects/spatial/guide-to-spatial-analysis-1.md
      - Spatial statistics: projects/spatial/guide-to-spatial-analysis-2.md
    - Math:
      - projects/math/index.md
      - Math, a practical odyssey: projects/math/math-practical-odyssey-1.ipynb 
    - Fun:
      - Model complexity vs accuracy - an empirical analysis: projects/fun/curve_fitting_model-complexity-vs-accuracy.ipynb
      - Verifying central limit theorem: projects/fun/verifying_central_limit_theorem.ipynb
      - Verifying central limit theorem in regression: projects/fun/verifying_clt_in_regression.ipynb
  - Apps:
    - apps/index.md
    - Fire map: apps/firemap.md
    - Wildfire hazard potential: apps/wildfire-hazard.md
    - Quake map: apps/quakemap.md
    - USA Pluscodes: apps/usa-pluscodes.md
    - Flask notes: apps/flask-notes.md
    - Fullstack Python app: apps/fullstack-python-webapp-1.md
  - Books:
    - GIS for Science - Climate Modeling chapter: books/2021-gis-for-science.md
    - Reviewer - Advanced Python Scripting for ArcGIS: books/2020-adv-py-scripting.md
    - Reviewer - Python Scripting for ArcGIS: books/2019-py-scripting.md
    - Reviewer - Essential Python: books/2018-essential-python.md
  - Talks:
    - 2024 FOSS4G North America: talks/2024-foss4gna.md
    - 2024 Anna Univ GeoInnovation Challenge - Keynote: talks/2024-annauniv-geoinnovation-challenge.md
    - 2021 Esri Developer Summit: talks/2021-esri-devsummit.md
    - 2020 Esri Training Seminar: talks/2020-esri-seminar.md
    - 2020 Esri Developer Summit: talks/2020-esri-devsummit.md
    - 2020 Spatial Data Science MOOC: talks/2020-spatial-ds-mooc.md
    - 2019 Esri Developer Summit: talks/2019-esri-devsummit.md
    - 2019 Directions Magazine Webinar: talks/2019-dirmag-webinar.md
    - 2019 FOSS4G North America: talks/2019-foss4gna.md
    - 2018 Esri Developer Summit: talks/2018-esri-devsummit.md
    - 2018 GeoDev Meetup: talks/2018-portland-geodev-meetup.md
    - 2017 GeoDev Meetup: talks/2017-geodev-webinar.md
    - 2017 Esri Developer Summit: talks/2017-esri-devsummit.md
    - 2017 Esri User Conference: talks/2017-esri-uc.md
    - 2015 Esri User Conference: talks/2015-esri-uc.md
  - Teaching Resources:
    - Programming:
      - Python:
        - Datatypes: teaching_resources/python/python_datatypes.ipynb
        - Numeric datatypes: teaching_resources/python/python_numeric_datatypes.ipynb
        - Conditional execution: teaching_resources/python/python_conditional_execution.ipynb
        - Functions: teaching_resources/python/python_functions.ipynb
        - Iteration: teaching_resources/python/python_iterations.ipynb
        - Exception handling: teaching_resources/python/python_exception_handling.ipynb
        - Classes: teaching_resources/python/python_classes.ipynb
        - Mutability: teaching_resources/python/python_mutability.ipynb
        - Memory: teaching_resources/python/python_memory.ipynb
        - Python language optimizations: teaching_resources/python/python_language_optimizations.ipynb
        - Conda package manager: teaching_resources/python/conda_pkg_manager.ipynb
        - Mamba package manager: teaching_resources/python/mamba_pkg_manager.md
      - Golang:
        - Intro: teaching_resources/golang/index.md
        - Basics: teaching_resources/golang/golang-basics.md
        - Datatypes: teaching_resources/golang/golang-datatypes.md
        - Control structures: teaching_resources/golang/golang-control-flow.md
        - Goroutines: teaching_resources/golang/goroutine.md
      - Octave:
        - Loops, conditional execution, functions: teaching_resources/octave/octave_loops_conditional_functions.md
        - Plotting: teaching_resources/octave/octave_plotting.md
      - R programming:
        - Datatypes, variables: teaching_resources/r/r_datatypes_variables.ipynb
      - Front end development:
        - HTML: teaching_resources/front-end/html.md
        - Javascript: teaching_resources/front-end/js_essentials.md
        - Web development: teaching_resources/front-end/web_development.md
    - Data analysis:
      - NumPy:
        - Array creation: teaching_resources/numpy/numpy_array_creation.ipynb
        - Array searching: teaching_resources/numpy/numpy_array_searching.ipynb
      - Pandas:
        - DataFrame creation, exploration: teaching_resources/pandas/pandas_df_creation_exploration.ipynb
        - Indices, sorting, merging: teaching_resources/pandas/pandas_indices_sorting_merging.ipynb
        - Unique, isnull, time series: teaching_resources/pandas/pandas_unique_time_series.ipynb
        - Data visualization: teaching_resources/pandas/pandas_data_viz_1.ipynb
      - Matplotlib:
        - Intro to subplots: teaching_resources/matplotlib/matplotlib_intro_subplots.ipynb
        - Working with axes: teaching_resources/matplotlib/matplotlib_working_with_axes.ipynb
        - Geographical plotting: teaching_resources/matplotlib/matplotlib_geo.ipynb
      - Seaborn:
        - Intro & Exploring distributions: teaching_resources/seaborn/seaborn_exploring_distributions.ipynb
        - Categorical plotting: teaching_resources/seaborn/seaborn_categorical_plotting.ipynb
        - Matrix and regression plots: teaching_resources/seaborn/seaborn_matrix_regression.ipynb
        - Grids and customizations: teaching_resources/seaborn/seaborn_grids_customization.ipynb
      - Plotly:
        - Getting started: teaching_resources/plotly/plotly_getting_started.ipynb
        - Plotting with Pandas: teaching_resources/plotly/plotly_plotting_with_pandas.ipynb
        - Geographical plotting: teaching_resources/plotly/plotly_geographical_plotting.ipynb
      - SQL:
        - Intro, CRUD operations: teaching_resources/sql/sql_crud.md
        - Query operators: teaching_resources/sql/sql_query_operators.md
        - SQL In Depth: teaching_resources/sql/sql_in_depth_1.md
        - Joins: teaching_resources/sql/sql_joins.md
        - SQL problem sets 1: teaching_resources/sql/sql_problem_sets_1.md
    - Geospatial:
      - GDAL & OGR:
        - Intro: teaching_resources/gdal/gdal_intro.md
        - Inspecting rasters: teaching_resources/gdal/gdal_inspecting_rasters.ipynb
        - Mosaicking, warping, pansharpening: teaching_resources/gdal/gdal_mosaicking_warping_pansharpening.ipynb
        - Interacting with WMS: teaching_resources/gdal/gdal_wms.ipynb
        - OGR - inspection, ogr2ogr: teaching_resources/gdal/ogr_inspection_ogr2ogr.ipynb
      - Geopandas:
        - Intro and plotting: teaching_resources/geopandas/geopandas_intro_plotting.ipynb
        - Geocoding and interactive plotting: teaching_resources/geopandas/geopandas_geocoding_interactive_plotting.ipynb
        - Spatial overlays: teaching_resources/geopandas/geopandas_spatial_overlays.ipynb
        - Reclass, PySAL, OSM: teaching_resources/geopandas/geopandas_reclass_pysal_osm.ipynb
      - Rasterio:
        - Intro, inspection, plotting: teaching_resources/rasterio/rasterio_inspection_plotting.ipynb
        - Working with Hyperspectral data: teaching_resources/rasterio/rasterio_hyperspectral.ipynb
      - Xarray:
        - Intro, inspection, plotting: teaching_resources/xarray/xarray_intro.ipynb
        - Working with multidimensional data: teaching_resources/xarray/xarray_multidim_dataset.ipynb
      - PostGIS:
        - Intro, spatial queries: teaching_resources/postgis/postgis_intro.md
        - Sqlalchemy, Geopandas: teaching_resources/postgis/postgis_sqlalchemy_gpd.ipynb
    - Tools:
      - Docker: teaching_resources/tools/docker-1.md
      - Grep - CLI word finder: teaching_resources/tools/grep-1.md
      - gsutil - GCP storage CLI: teaching_resources/tools/gsutil-1.md
      - kubectl - GKE CLI: teaching_resources/tools/kubectl-1.md
      - Helm charts: teaching_resources/tools/helm-1.md
      - Yaml syntax: teaching_resources/tools/yaml_syntax.md
      - Latex - Math and Equation fonts: teaching_resources/tools/latex-1.ipynb

  - Blog: blog/index.md

theme: 
  name: material
  logo: images/scatter-128.png
  favicon: images/favicon.ico
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.path
    - navigation.indexes
    - search.suggest
    - search.highlight

plugins:
  - mkdocs-jupyter
  - search
  - blog:
      archive: false
      pagination_per_page: 5
      blog_toc: true

extra:
  analytics:
    provider: google
    property: UA-113202945-1

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
