site_name: Atma Mani's blog
nav:
  - Home: index.md
  - Talks: talks.md
  - Articles: articles/readme.md
  - Cheatsheets: cheatsheets/readme.md
  - Apps: apps.md
theme:
  name: 'material'
  palette:
    primary: 'teal'
    accent: 'deep orange'
  logo:
    icon: 'blur_on'
  favicon: 'static/favicon.svg'
  highlightjs: true
  # hljs_languages:
  #   - python
  #   - r
  #   - yaml
copyright: 'Copyright &copy; 2019 - 2020 Atma Mani'

# Plugins
plugins:
 - mknotebooks:
    execute: false

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
      noclasses: false
      use_pygments: true
  - toc:
      permalink: true
